name: Convert Manifest ODT → FODT + PDF

on:
  push:
    paths:
      - 'manifest/*.odt'

jobs:
  convert:
    uses: ./.github/workflows/_convert-odt-base.yml
    with:
      folder: 'manifest'
    secrets: inherit
