name: Convert Dutch ODT → FODT + PDF

on:
  push:
    paths:
      - 'translations/Dutch/*.odt'

jobs:
  convert:
    uses: ./.github/workflows/_convert-odt-base.yml
    with:
      folder: 'translations/Dutch'
    secrets: inherit
